Make PerfGazer.close idempotent (#34)
In DBR 16 PerfGazer.close() is called multiple times (because DBR 16
seems to actually call `onApplicationEnd`, different from DBR 13).
It can cause failures / race conditions. Better to assume there can be
multiple calls to close(), and all are handled properly.

See the logs proving that `.close()` is called multiple times: 
```
26/04/17 16:10:33 INFO PerfGazer$: Listener closed, size of maps sql=0 and job=0)
26/04/17 16:10:34 INFO PerfGazer$: Listener closed, size of maps sql=0 and job=0)
```

## Motivation

Avoid errors like: 

```
com.databricks.backend.common.rpc.SparkStoppedException: Spark down: 
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:774)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:859)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$runInnerLoop$1(DriverWrapper.scala:630)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.logging.AttributionContextTracing.$anonfun$withAttributionContext$1(AttributionContextTracing.scala:49)
	at com.databricks.logging.AttributionContext$.$anonfun$withValue$1(AttributionContext.scala:293)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:289)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext(AttributionContextTracing.scala:47)
	at com.databricks.logging.AttributionContextTracing.withAttributionContext$(AttributionContextTracing.scala:44)
	at com.databricks.backend.daemon.driver.DriverWrapper.withAttributionContext(DriverWrapper.scala:81)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:625)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:548)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:373)
	at java.lang.Thread.run(Thread.java:840)
Workload failed, see run output for details
```
for DBR 16.4.21, which seem to call onApplicationEnd properly.

## Description

This PR ensures PerfGazer.close() is handled atomically, and has effect
only once.

## Checklist

- [x] I have clearly described the motivation for this change above
- [x] This PR contains a single, focused change
- [x] Tests have been added/updated for the changes